[package]
name = "rust_flutter_ffi_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", 'staticlib', 'rlib']

[dependencies]
libc = "0"

[build-dependencies]
cbindgen = "0"
bindgen = "0"
